version: 0.2
  
phases:
  install:
    on-failure: ABORT
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing serverless CLI
      - npm i -g serverless@latest
      - echo Installing npm dependencies of notes service
      - npm install
  build:
    on-failure: ABORT
    commands:
      - echo Deploying resources
      - serverless deploy --stage temp
artifacts:
  files:
    - my-artifact/*
  name: MyProjectArtifacts
cache:
  paths:
    - 'node_modules/**/*'
privilege-mode: true